//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("OilModel", "FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "GasolineStations", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyOil.GasolineStation), "OilConsumeInfoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyOil.OilConsumeInfo), true)]
[assembly: EdmRelationshipAttribute("OilModel", "FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "GasolineTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyOil.GasolineType), "OilConsumeInfoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyOil.OilConsumeInfo), true)]
[assembly: EdmRelationshipAttribute("OilModel", "FK_OilConsumeInfoes_OilConsumeInfoes", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyOil.user), "OilConsumeInfoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyOil.OilConsumeInfo), true)]
[assembly: EdmRelationshipAttribute("OilModel", "FK_dbo_subMenus_dbo_SideMenus_menu_ID", "SideMenus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyOil.SideMenu), "SubMenus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyOil.SubMenu), true)]

#endregion

namespace MyOil
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class OilEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“OilEntities”部分中的连接字符串初始化新 OilEntities 对象。
        /// </summary>
        public OilEntities() : base("name=OilEntities", "OilEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OilEntities 对象。
        /// </summary>
        public OilEntities(string connectionString) : base(connectionString, "OilEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OilEntities 对象。
        /// </summary>
        public OilEntities(EntityConnection connection) : base(connection, "OilEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<C__MigrationHistory> C__MigrationHistory
        {
            get
            {
                if ((_C__MigrationHistory == null))
                {
                    _C__MigrationHistory = base.CreateObjectSet<C__MigrationHistory>("C__MigrationHistory");
                }
                return _C__MigrationHistory;
            }
        }
        private ObjectSet<C__MigrationHistory> _C__MigrationHistory;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<GasolineStation> GasolineStations
        {
            get
            {
                if ((_GasolineStations == null))
                {
                    _GasolineStations = base.CreateObjectSet<GasolineStation>("GasolineStations");
                }
                return _GasolineStations;
            }
        }
        private ObjectSet<GasolineStation> _GasolineStations;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<GasolineType> GasolineTypes
        {
            get
            {
                if ((_GasolineTypes == null))
                {
                    _GasolineTypes = base.CreateObjectSet<GasolineType>("GasolineTypes");
                }
                return _GasolineTypes;
            }
        }
        private ObjectSet<GasolineType> _GasolineTypes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OilConsumeInfo> OilConsumeInfoes
        {
            get
            {
                if ((_OilConsumeInfoes == null))
                {
                    _OilConsumeInfoes = base.CreateObjectSet<OilConsumeInfo>("OilConsumeInfoes");
                }
                return _OilConsumeInfoes;
            }
        }
        private ObjectSet<OilConsumeInfo> _OilConsumeInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SideMenu> SideMenus
        {
            get
            {
                if ((_SideMenus == null))
                {
                    _SideMenus = base.CreateObjectSet<SideMenu>("SideMenus");
                }
                return _SideMenus;
            }
        }
        private ObjectSet<SideMenu> _SideMenus;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SubMenu> SubMenus
        {
            get
            {
                if ((_SubMenus == null))
                {
                    _SubMenus = base.CreateObjectSet<SubMenu>("SubMenus");
                }
                return _SubMenus;
            }
        }
        private ObjectSet<SubMenu> _SubMenus;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user_enc> user_enc
        {
            get
            {
                if ((_user_enc == null))
                {
                    _user_enc = base.CreateObjectSet<user_enc>("user_enc");
                }
                return _user_enc;
            }
        }
        private ObjectSet<user_enc> _user_enc;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 C__MigrationHistory EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToC__MigrationHistory(C__MigrationHistory c__MigrationHistory)
        {
            base.AddObject("C__MigrationHistory", c__MigrationHistory);
        }
    
        /// <summary>
        /// 用于向 GasolineStations EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGasolineStations(GasolineStation gasolineStation)
        {
            base.AddObject("GasolineStations", gasolineStation);
        }
    
        /// <summary>
        /// 用于向 GasolineTypes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGasolineTypes(GasolineType gasolineType)
        {
            base.AddObject("GasolineTypes", gasolineType);
        }
    
        /// <summary>
        /// 用于向 OilConsumeInfoes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOilConsumeInfoes(OilConsumeInfo oilConsumeInfo)
        {
            base.AddObject("OilConsumeInfoes", oilConsumeInfo);
        }
    
        /// <summary>
        /// 用于向 SideMenus EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSideMenus(SideMenu sideMenu)
        {
            base.AddObject("SideMenus", sideMenu);
        }
    
        /// <summary>
        /// 用于向 SubMenus EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSubMenus(SubMenu subMenu)
        {
            base.AddObject("SubMenus", subMenu);
        }
    
        /// <summary>
        /// 用于向 users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// 用于向 user_enc EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouser_enc(user_enc user_enc)
        {
            base.AddObject("user_enc", user_enc);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="C__MigrationHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C__MigrationHistory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 C__MigrationHistory 对象。
        /// </summary>
        /// <param name="migrationId">MigrationId 属性的初始值。</param>
        /// <param name="model">Model 属性的初始值。</param>
        /// <param name="productVersion">ProductVersion 属性的初始值。</param>
        public static C__MigrationHistory CreateC__MigrationHistory(global::System.String migrationId, global::System.Byte[] model, global::System.String productVersion)
        {
            C__MigrationHistory c__MigrationHistory = new C__MigrationHistory();
            c__MigrationHistory.MigrationId = migrationId;
            c__MigrationHistory.Model = model;
            c__MigrationHistory.ProductVersion = productVersion;
            return c__MigrationHistory;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MigrationId
        {
            get
            {
                return _MigrationId;
            }
            set
            {
                if (_MigrationId != value)
                {
                    OnMigrationIdChanging(value);
                    ReportPropertyChanging("MigrationId");
                    _MigrationId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MigrationId");
                    OnMigrationIdChanged();
                }
            }
        }
        private global::System.String _MigrationId;
        partial void OnMigrationIdChanging(global::System.String value);
        partial void OnMigrationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Model
        {
            get
            {
                return StructuralObject.GetValidValue(_Model);
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.Byte[] _Model;
        partial void OnModelChanging(global::System.Byte[] value);
        partial void OnModelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductVersion
        {
            get
            {
                return _ProductVersion;
            }
            set
            {
                OnProductVersionChanging(value);
                ReportPropertyChanging("ProductVersion");
                _ProductVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductVersion");
                OnProductVersionChanged();
            }
        }
        private global::System.String _ProductVersion;
        partial void OnProductVersionChanging(global::System.String value);
        partial void OnProductVersionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="GasolineStation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GasolineStation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 GasolineStation 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="lge">lge 属性的初始值。</param>
        /// <param name="lae">lae 属性的初始值。</param>
        public static GasolineStation CreateGasolineStation(global::System.Int32 id, global::System.Single lge, global::System.Single lae)
        {
            GasolineStation gasolineStation = new GasolineStation();
            gasolineStation.id = id;
            gasolineStation.lge = lge;
            gasolineStation.lae = lae;
            return gasolineStation;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single lge
        {
            get
            {
                return _lge;
            }
            set
            {
                OnlgeChanging(value);
                ReportPropertyChanging("lge");
                _lge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lge");
                OnlgeChanged();
            }
        }
        private global::System.Single _lge;
        partial void OnlgeChanging(global::System.Single value);
        partial void OnlgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single lae
        {
            get
            {
                return _lae;
            }
            set
            {
                OnlaeChanging(value);
                ReportPropertyChanging("lae");
                _lae = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lae");
                OnlaeChanged();
            }
        }
        private global::System.Single _lae;
        partial void OnlaeChanging(global::System.Single value);
        partial void OnlaeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String place
        {
            get
            {
                return _place;
            }
            set
            {
                OnplaceChanging(value);
                ReportPropertyChanging("place");
                _place = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("place");
                OnplaceChanged();
            }
        }
        private global::System.String _place;
        partial void OnplaceChanging(global::System.String value);
        partial void OnplaceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "OilConsumeInfoes")]
        public EntityCollection<OilConsumeInfo> OilConsumeInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OilConsumeInfo>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "OilConsumeInfoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OilConsumeInfo>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "OilConsumeInfoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="GasolineType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GasolineType : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 GasolineType 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static GasolineType CreateGasolineType(global::System.Int32 id)
        {
            GasolineType gasolineType = new GasolineType();
            gasolineType.id = id;
            return gasolineType;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "OilConsumeInfoes")]
        public EntityCollection<OilConsumeInfo> OilConsumeInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OilConsumeInfo>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "OilConsumeInfoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OilConsumeInfo>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "OilConsumeInfoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="OilConsumeInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OilConsumeInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OilConsumeInfo 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="totalCost">totalCost 属性的初始值。</param>
        /// <param name="oilprice">Oilprice 属性的初始值。</param>
        /// <param name="oilQuantity">oilQuantity 属性的初始值。</param>
        public static OilConsumeInfo CreateOilConsumeInfo(global::System.Int32 id, global::System.Decimal totalCost, global::System.Decimal oilprice, global::System.Decimal oilQuantity)
        {
            OilConsumeInfo oilConsumeInfo = new OilConsumeInfo();
            oilConsumeInfo.id = id;
            oilConsumeInfo.totalCost = totalCost;
            oilConsumeInfo.Oilprice = oilprice;
            oilConsumeInfo.oilQuantity = oilQuantity;
            return oilConsumeInfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal totalCost
        {
            get
            {
                return _totalCost;
            }
            set
            {
                OntotalCostChanging(value);
                ReportPropertyChanging("totalCost");
                _totalCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalCost");
                OntotalCostChanged();
            }
        }
        private global::System.Decimal _totalCost;
        partial void OntotalCostChanging(global::System.Decimal value);
        partial void OntotalCostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Oilprice
        {
            get
            {
                return _Oilprice;
            }
            set
            {
                OnOilpriceChanging(value);
                ReportPropertyChanging("Oilprice");
                _Oilprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Oilprice");
                OnOilpriceChanged();
            }
        }
        private global::System.Decimal _Oilprice;
        partial void OnOilpriceChanging(global::System.Decimal value);
        partial void OnOilpriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal oilQuantity
        {
            get
            {
                return _oilQuantity;
            }
            set
            {
                OnoilQuantityChanging(value);
                ReportPropertyChanging("oilQuantity");
                _oilQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oilQuantity");
                OnoilQuantityChanged();
            }
        }
        private global::System.Decimal _oilQuantity;
        partial void OnoilQuantityChanging(global::System.Decimal value);
        partial void OnoilQuantityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String refuelTime
        {
            get
            {
                return _refuelTime;
            }
            set
            {
                OnrefuelTimeChanging(value);
                ReportPropertyChanging("refuelTime");
                _refuelTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("refuelTime");
                OnrefuelTimeChanged();
            }
        }
        private global::System.String _refuelTime;
        partial void OnrefuelTimeChanging(global::System.String value);
        partial void OnrefuelTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_UserId
        {
            get
            {
                return _user_UserId;
            }
            set
            {
                Onuser_UserIdChanging(value);
                ReportPropertyChanging("user_UserId");
                _user_UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_UserId");
                Onuser_UserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _user_UserId;
        partial void Onuser_UserIdChanging(Nullable<global::System.Int32> value);
        partial void Onuser_UserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gs_id
        {
            get
            {
                return _gs_id;
            }
            set
            {
                Ongs_idChanging(value);
                ReportPropertyChanging("gs_id");
                _gs_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gs_id");
                Ongs_idChanged();
            }
        }
        private Nullable<global::System.Int32> _gs_id;
        partial void Ongs_idChanging(Nullable<global::System.Int32> value);
        partial void Ongs_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gt_id
        {
            get
            {
                return _gt_id;
            }
            set
            {
                Ongt_idChanging(value);
                ReportPropertyChanging("gt_id");
                _gt_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gt_id");
                Ongt_idChanged();
            }
        }
        private Nullable<global::System.Int32> _gt_id;
        partial void Ongt_idChanging(Nullable<global::System.Int32> value);
        partial void Ongt_idChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "GasolineStations")]
        public GasolineStation GasolineStation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GasolineStation>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "GasolineStations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GasolineStation>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "GasolineStations").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GasolineStation> GasolineStationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GasolineStation>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "GasolineStations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GasolineStation>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineStations_gs_id", "GasolineStations", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "GasolineTypes")]
        public GasolineType GasolineType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GasolineType>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "GasolineTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GasolineType>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "GasolineTypes").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GasolineType> GasolineTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GasolineType>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "GasolineTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GasolineType>("OilModel.FK_dbo_OilConsumeInfoes_dbo_GasolineTypes_gt_id", "GasolineTypes", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_OilConsumeInfoes_OilConsumeInfoes", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("OilModel.FK_OilConsumeInfoes_OilConsumeInfoes", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("OilModel.FK_OilConsumeInfoes_OilConsumeInfoes", "user").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("OilModel.FK_OilConsumeInfoes_OilConsumeInfoes", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("OilModel.FK_OilConsumeInfoes_OilConsumeInfoes", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="SideMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SideMenu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SideMenu 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        public static SideMenu CreateSideMenu(global::System.Int32 id, global::System.String title)
        {
            SideMenu sideMenu = new SideMenu();
            sideMenu.ID = id;
            sideMenu.Title = title;
            return sideMenu;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_dbo_subMenus_dbo_SideMenus_menu_ID", "SubMenus")]
        public EntityCollection<SubMenu> SubMenus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubMenu>("OilModel.FK_dbo_subMenus_dbo_SideMenus_menu_ID", "SubMenus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubMenu>("OilModel.FK_dbo_subMenus_dbo_SideMenus_menu_ID", "SubMenus", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="SubMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubMenu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SubMenu 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static SubMenu CreateSubMenu(global::System.Int32 id)
        {
            SubMenu subMenu = new SubMenu();
            subMenu.ID = id;
            return subMenu;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> menu_ID
        {
            get
            {
                return _menu_ID;
            }
            set
            {
                Onmenu_IDChanging(value);
                ReportPropertyChanging("menu_ID");
                _menu_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("menu_ID");
                Onmenu_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _menu_ID;
        partial void Onmenu_IDChanging(Nullable<global::System.Int32> value);
        partial void Onmenu_IDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static user Createuser(global::System.Int32 id)
        {
            user user = new user();
            user.ID = id;
            return user;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PWD
        {
            get
            {
                return _PWD;
            }
            set
            {
                OnPWDChanging(value);
                ReportPropertyChanging("PWD");
                _PWD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PWD");
                OnPWDChanged();
            }
        }
        private global::System.String _PWD;
        partial void OnPWDChanging(global::System.String value);
        partial void OnPWDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OilModel", "FK_OilConsumeInfoes_OilConsumeInfoes", "OilConsumeInfoes")]
        public EntityCollection<OilConsumeInfo> OilConsumeInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OilConsumeInfo>("OilModel.FK_OilConsumeInfoes_OilConsumeInfoes", "OilConsumeInfoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OilConsumeInfo>("OilModel.FK_OilConsumeInfoes_OilConsumeInfoes", "OilConsumeInfoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OilModel", Name="user_enc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_enc : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user_enc 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static user_enc Createuser_enc(global::System.Int32 id)
        {
            user_enc user_enc = new user_enc();
            user_enc.ID = id;
            return user_enc;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PWD
        {
            get
            {
                return _PWD;
            }
            set
            {
                OnPWDChanging(value);
                ReportPropertyChanging("PWD");
                _PWD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PWD");
                OnPWDChanged();
            }
        }
        private global::System.String _PWD;
        partial void OnPWDChanging(global::System.String value);
        partial void OnPWDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion
    
    }

    #endregion
    
}
